version: "3"

tasks:
  build-automaton:
    dir: automaton
    cmds:
      - GOOS=js GOARCH=wasm go build -o ../static/automaton.wasm .

  start-docker:
    cmds:
      - docker build -t laciudad:dev .
      - docker run --env-file=.env --net=host laciudad:dev

  publish-docker:
    cmds:
      - docker build -t minskylab/laciudadinvisible .
      - docker push minskylab/laciudadinvisible

  publish-helm:
    cmds:
      - task: publish-docker
      - helm push laciudad/ minsky

  start:
    cmds:
      - task: build-automaton
      - pipenv run python main.py
